//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphApplication.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphApplication.Common.GraphResource", typeof(GraphResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add null node to graph..
        /// </summary>
        internal static string Error_CannotAddNullNode {
            get {
                return ResourceManager.GetString("Error_CannotAddNullNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add null vertex to graph..
        /// </summary>
        internal static string Error_CannotAddNullVertex {
            get {
                return ResourceManager.GetString("Error_CannotAddNullVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot traverse graph with no node..
        /// </summary>
        internal static string Error_CannotTraverseGraphWithoutNode {
            get {
                return ResourceManager.GetString("Error_CannotTraverseGraphWithoutNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot traverse null or empty graph..
        /// </summary>
        internal static string Error_CannotTraverseNullOrEmptyGraph {
            get {
                return ResourceManager.GetString("Error_CannotTraverseNullOrEmptyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node destination vertex not exist in graph..
        /// </summary>
        internal static string Error_DestinationVertexNotExist {
            get {
                return ResourceManager.GetString("Error_DestinationVertexNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node already added to graph..
        /// </summary>
        internal static string Error_DuplicateNode {
            get {
                return ResourceManager.GetString("Error_DuplicateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex already added to graph..
        /// </summary>
        internal static string Error_DuplicateVertex {
            get {
                return ResourceManager.GetString("Error_DuplicateVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To traverse graph start vertex must exist in graph..
        /// </summary>
        internal static string Error_GraphNotContainsStartVertex {
            get {
                return ResourceManager.GetString("Error_GraphNotContainsStartVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost cannot be less than or equal to zero..
        /// </summary>
        internal static string Error_InvalidCost {
            get {
                return ResourceManager.GetString("Error_InvalidCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add node with null vertex to graph..
        /// </summary>
        internal static string Error_NullDestinationVertex {
            get {
                return ResourceManager.GetString("Error_NullDestinationVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add node to null source..
        /// </summary>
        internal static string Error_NullSourceVertex {
            get {
                return ResourceManager.GetString("Error_NullSourceVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To traverse graph start vertex cannot be null..
        /// </summary>
        internal static string Error_NullStartVertex {
            get {
                return ResourceManager.GetString("Error_NullStartVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source vertex not exist in graph..
        /// </summary>
        internal static string Error_SourceVertexNotExist {
            get {
                return ResourceManager.GetString("Error_SourceVertexNotExist", resourceCulture);
            }
        }
    }
}
